name: Build mod
on:
  workflow_dispatch: 

env:
  GAMEFOLDER: ./bannerlord    

jobs:
  build_submodule:
    runs-on: ubuntu-latest
    steps:
    - name: Setup repo
      uses: actions/checkout@v5
    - name: Set GameFolder absolute path
      run: |
        echo "gamefolder=$(realpath $GAMEFOLDER)" >> $GITHUB_ENV
    - name: Ensure GameFolder path exists
      run: mkdir -p "$GAMEFOLDER"
    - name: Build
      run: dotnet build -c Release "-p:GameFolder=$GAMEFOLDER" src/
    - name: Upload assets
      uses: actions/upload-artifact@v4
      with:
        name: ButterAchievements
        if-no-files-found: error
        path: |
          ${{ env.GAMEFOLDER }}/Modules/
          !${{ env.GAMEFOLDER }}/Modules/Native
          !${{ env.GAMEFOLDER }}/Modules/SandBox
          !${{ env.GAMEFOLDER }}/Modules/StoryMode
