name: Build mod
on:
  workflow_dispatch: 

jobs:
  build_submodule:
    runs-on: ubuntu-latest
    steps:
    - name: Setup repo
      uses: actions/checkout@v5
    - name: Get GameFolder path
      run: |
        mkdir -p ./bannerlord
        echo "gamefolder=./bannerlord" >> $GITHUB_ENV
    - name: Build
      run: dotnet build -c Release -p:GameFolder="$gamefolder"
    - name: Upload assets
      uses: actions/upload-artifact@v4
      with:
        name: ButterAchievements
        if-no-files-found: error
        path: |
          bannerlord/Modules/
          !bannerlord/Modules/Native
          !bannerlord/Modules/SandBox
          !bannerlord/Modules/StoryMode
